### ISSUE TITLE
Rate Limiting, is it comma or colon? 

### ISSUE THREAD

**Issue by abdusfauzi** [mettle/sendportal-docs#3]
at this document, https://github.com/mettle/sendportal-docs/blob/master/api-introduction.md the description use `,` as divider between request and minute.

however, the code sample use `:`.

which one is the correct one?

**Comment by JonoB** [comment]
Thanks for reporting - fixed in https://github.com/mettle/sendportal-docs/commit/4f8dd7e2c883009d19d67263c51cb27591fd17d2
